hydra:
  run:
    dir: <path_to_repo>/${model.name}/${now:%Y-%m-%d_%H%M%S}

gt_path: <path_to_repo>/gt_tracks
running_locally: False


weights_path: <path_to_repo>/pretrained_weights/weights_finetuned_ec.ckpt

track_name: shitomasi_custom
representation: time_surfaces_v2_5
patch_size: 31
visualize: False
dt_track_vis: 0.2

# Composing nested config with default
defaults:
  - model: correlation3_unscaled
# Pytorch lightning trainer's argument
trainer:
  gpus: [0]
