hydra:
  run:
    dir:  C:/Users/lplet/Documents/TUDelft/MSC/Y1/DL/Project/group_branch/deep_ev_tracker_repro/outputs/${data.name}/${model.name}/${experiment}/${now:%Y-%m-%d_%H%M%S}

gt_path: C:/Users/lplet/Documents/TUDelft/MSC/Y1/DL/Project/group_branch/deep_ev_tracker_repro/gt_tracks
running_locally: False


weights_path: C:/Users/lplet/Documents/TUDelft/MSC/Y1/DL/Project/group_branch/deep_ev_tracker_repro/pretrained_weights/weights_finetuned_ec.ckpt

track_name: shitomasi_custom
representation: time_surfaces_v2_5
patch_size: 31
visualize: False
dt_track_vis: 0.2

# Composing nested config with default
defaults:
  - model: correlation3_unscaled
# Pytorch lightning trainer's argument
trainer:
  gpus: 0
